### ISSUE TITLE
include non-minified js file in the distribution

### ISSUE THREAD

**Issue by erwin16** [khoanguyen96/vue-paypal-checkout#10]
Thanks for your awesome work ! 
For helping developers in debugging, could it be possible to include also the non-minified version if the js file ...  we'll load it via webpack..  thanks a lot

**Comment by khoanguyen96** [comment]
Hey @erwin16,

I included a non-minified umd version in the [`dist`](https://github.com/khoanguyen96/vue-paypal-checkout/tree/master/dist) directory.

Hope that helps!

**Comment by erwin16** [comment]
thanks a lot
