### ISSUE TITLE
button style not working as expected

### ISSUE THREAD

**Issue by erwin16** [khoanguyen96/vue-paypal-checkout#11]
I am trying to use specific button styles as described in the doc ... but the label, locale, size , color and shape are not taken in account
script

      `
      <script>
	import TopNavTwo from '@/components/TopNavTwo'
	import PageHeader from '@/components/PageHeader'
	import PayPal from 'vue-paypal-checkout'
	export default {
	  mounted () {
	    document.body.scrollTop = document.documentElement.scrollTop = 0
	  },
	  data () {
	    return {
	      credentials: {
	        sandbox: '<sandbox client id>',
	        production: '<production client id>'
	      },
	      aStyle: { label: 'pay', locale: 'fr_FR', size: 'small', shape: 'rect', color: 'blue' },
	      bStyle: { label: 'pay', locale: 'fr_FR', size: 'small', shape: 'rect', color: 'gold' }
	    }
	  },
	  components: { PageHeader, TopNavTwo, PayPal }
	}
	</script>
`
html 

      `<PayPal :buttonStyle="aStyle" :client="credentials" amount="10.00" currency="EUR" env="sandbox" invoice-number="john@whitehouse.com"></PayPal>
        <PayPal :buttonStyle="bStyle" :client="credentials" amount="10.00" currency="EUR" env="sandbox" invoice-number="john@whitehouse.com"></PayPal>`

**Comment by khoanguyen96** [comment]
Hey @erwin16,

Thanks for the catch! I seemed to mess up and not include the buttonStyle for a recent release. It should be fixed now.

I'll publish a new version soon :+1:

**Comment by erwin16** [comment]
thanks a lot

**Comment by koddr** [comment]
Hello. 

Why `:buttonStyle` is not working at `2.3.5` version? I try to do this:

```js
// ./js/script.js

// Include libraries
import Vue from 'vue'
import PayPal from 'vue-paypal-checkout'

// Vue
const app = new Vue({
  el: '#app',
  components: {
    PayPal
  },
  data: {
    paypal_api_keys: {
      sandbox: '<sandbox client id>',
      production: '<production client id>'
    },
    paypal_button_style: {
      label: 'pay',
      size: 'medium',
      shape: 'pill',
      color: 'blue'
    },
    ...
  },
  ...
})
```

On template:

```html
<!-- ./index.html -->

<div id="app">
  <pay-pal
    :amount="10.0"
    :currency="USD"
    :client="paypal_api_keys"
    :buttonStyle="paypal_button_style"
    env="sandbox">
  </pay-pal>
</div>

<script src="./js/script.min.js"></script>
```

...and alway get gold button with small size! How to solve this? Please.

**Comment by khoanguyen96** [comment]
Hey, @koddr

How are you importing the button component? Additionally, are you using webpack with vue-loader?

I can't seem to reproduce this. If you're still experiencing this after checking the package version, and etc, I'll take a closer look later if you want!

[JSFiddle](https://jsfiddle.net/khoanguyen96/n8t40zd7/2/) with your styles.

Cheers!

**Comment by koddr** [comment]
Yes, kebab-case save lives 👍
