### ISSUE TITLE
How to change the locale used bt the button ?

### ISSUE THREAD

**Issue by erwin16** [khoanguyen96/vue-paypal-checkout#14]
I tried locale: 'fr_FR' , but it does not change the button... seems your are using the browser locale wo taking in account the locale: 'fr_FR' . parameter ?

**Comment by khoanguyen96** [comment]
Hey @erwin16,

The locale is it's own separate configurable parameter, as documented from [`paypal-checkout`'s docs](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md#customizing-the-button).

Currently, `vue-paypal-checkout` doesn't have that option configurable. I'll add it soon thanks!

**Comment by khoanguyen96** [comment]
Published in v2.3.3! :rocket:

**Comment by erwin16** [comment]
thanks a lot !!!  awesome ... working fine ... I would like PayPal dev to be so reactive and efficient as you are...   I am fighting today with the Sandbox , not being able to create buyers accounts .. only business accounts can be created...
