### ISSUE TITLE
Warning on locale prop ?

### ISSUE THREAD

**Issue by erwin16** [khoanguyen96/vue-paypal-checkout#16]
According to your doc for local prop, I used:

    `<PayPal v-show="displayPaypalButtons" :buttonStyle="aStyle" locale="fr_FR" :client="credentials" amount="10.00" currency="EUR" env="sandbox" :invoice-number="invoiceNumber"></PayPal>

It  workd ...but  I get a . warning message 

    `Invalid prop: type check failed for prop "locale". Expected Object, got String.

**Comment by erwin16** [comment]
sorry oops ... cache loading issue .. working fine !

**Comment by khoanguyen96** [comment]
Hey @erwin16,

Thanks for the warning report! It's fixed now in the latest release. Regardless, it was just a warning! I'm glad the `locale` works for you now :+1:
