### ISSUE TITLE
Notification url

### ISSUE THREAD

**Issue by l770277** [khoanguyen96/vue-paypal-checkout#18]
Hi possible is add to props a key of 'notification_url'.
I mean a place for IPN
 

> PayPal posts HTML FORM variables to a program at a URL you specify. You can specify this URL either in your account profile or with the notify_url variable on each transaction.

**Comment by khoanguyen96** [comment]
Hey @l770277,

Is there a link to the official PayPal docs I can reference from? If I'm reading this correctly this would be part of the transaction object... correct?

**Comment by l770277** [comment]
https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/formbasics/

**Comment by khoanguyen96** [comment]
Hey @l770277,

So after reading the docs carefully, I've added a `notify-url` prop to the transaction object instead. As the docs you referenced for me seemed to be referring to the PayPal Button for an HTML form which differs significantly from [`paypal-checkout`](https://github.com/paypal/paypal-checkout).

```
notify_url string
The URL to send payment notifications.
```

If you want I can publish a beta you can try testing out? I've added it in the [feat/add-notify_url branch](https://github.com/khoanguyen96/vue-paypal-checkout/tree/feat/add-notify_url)

**Comment by khoanguyen96** [comment]
Published Beta! `vue-paypal-checkout@2.3.4-beta.1`

**Comment by l770277** [comment]
Very thanks!

**Comment by khoanguyen96** [comment]
Hey @l770277,

Did it work? If so, I'll merge it back to master and publish it officially.

Cheers!

**Comment by l770277** [comment]
Hi, yes it works properly

**Comment by khoanguyen96** [comment]
Hey,

`vue-paypal-checkout@2.3.5` published! :rocket:

Please tell me if anything changed. It shouldn't haha.
