### ISSUE TITLE
Allow "style" binding?

### ISSUE THREAD

**Issue by dvlden** [khoanguyen96/vue-paypal-checkout#2]
```
style: {
    label: 'checkout',
    size:  'responsive',    // small | medium | large | responsive
    shape: 'pill',     // pill | rect
    color: 'gold'      // gold | blue | silver | black
}
```

I tried editing your package directly as I need this importantly for an specific project, but seems like it's loading compiled file and not vue file components?

Appreciate it if you can implement this soon.

**Comment by khoanguyen96** [comment]
Hey,

Sorry about that! I completely forgot about the style customization `paypal-checkout` offers. I'll definitely take a look into implementing it soon.

**Comment by khoanguyen96** [comment]
Hey, just added it as a `buttonStyle` prop. It's in `v2.1.2`

**Comment by dvlden** [comment]
Great! Much appreciated. It's really useful package!

**Comment by dvlden** [comment]
I believe it's supposed to be `gold` and not `orange`?

<img width="1920" alt="screen shot 2017-09-02 at 11 45 58" src="https://user-images.githubusercontent.com/3460368/29994626-5f1db288-8fd4-11e7-9823-bc4f8efe569c.png">

**Comment by khoanguyen96** [comment]
Oh my bad! I referenced the colors from here [button.md](https://github.com/paypal/paypal-checkout/blob/master/docs/button.md)

I'll change it real quick.

**Comment by AkslDev** [comment]
Hello, i just want to know if it possible to personnalize more the button paypal ? For add my style with my css for example ?
