### ISSUE TITLE
A subscription

### ISSUE THREAD

**Issue by l770277** [khoanguyen96/vue-paypal-checkout#21]
Hi, how to create button type of subscription payment?

**Comment by khoanguyen96** [comment]
Hey @l770277,

From my brief look I think the `paypal-checkout` button is only for one time Payments. If you would like to create a subscription payment... maybe [Billing API](https://developer.paypal.com/docs/api/payments.billing-plans) might be what you're looking for?

Again... Sorry I'm not too sure.
