### ISSUE TITLE
Why is this package packed so large?

### ISSUE THREAD

**Issue by lilywang711** [khoanguyen96/vue-paypal-checkout#30]
![image](https://user-images.githubusercontent.com/17040010/37814848-31328bf6-2ea7-11e8-91c7-5a07d27e25ab.png)
hi~
I'am comfused why is this package packed so large?
Is there any way to reduce its size?
I used vue-cli to build the program
thanks~

**Comment by khoanguyen96** [comment]
Hey @lilywang711,

This is a Vue.js wrapper for [`paypal-checkout`]
Most of the size is probably inherited from its parent package.

There's a [related issue](https://github.com/paypal/paypal-checkout/issues/443) here.

I'm not knowledgable enough to know if there's anyway to reduce the size.

[`paypal-checkout`]:https://github.com/paypal/paypal-checkout

**Comment by kieraneglin** [comment]
@khoanguyen96 There is a link to a minified version of the script that's 10% of the current script's size.  Is there any way you could look into integrating the smaller script with this library?
