### ISSUE TITLE
I have used a band card in my account, why at the second time to use still need bind a card ?

### ISSUE THREAD

**Issue by moonshineBoy** [khoanguyen96/vue-paypal-checkout#52]
I input a card information when I use the PayPal for payment, and success, then in my account I can fond the card, see the bellow snapshot:

![60d8b185-6091-45b3-a08e-0d83e814c2db](https://user-images.githubusercontent.com/22514729/41810382-f77544d6-772f-11e8-8ad0-5f7323d63495.png)

Now,  I use the account for second payment, it still need a more band card.

![image](https://user-images.githubusercontent.com/22514729/41810439-ec4b1846-7730-11e8-9532-a8a268ef6a9c.png)

if I input the first card number, it will say 
 
![image](https://user-images.githubusercontent.com/22514729/41810435-d2392e66-7730-11e8-83c7-90f98d676cb2.png)

**Comment by khoanguyen96** [comment]
Hey, sorry this is out of my control. Seems to be expected behavior.
