### ISSUE TITLE
how to write the address 

### ISSUE THREAD

**Issue by mjfxdd** [khoanguyen96/vue-paypal-checkout#68]
I don't know how to send the address to paypal. I hope I can choose the address on the page and pass it to PayPal instead of checking the address in PayPal after it logs in.  
Can you tell me how to transmit and how to write the data?
Thank you very much.
![image](https://user-images.githubusercontent.com/24537314/48886674-cf31f500-ee67-11e8-85d1-afd7d503c9dd.png)

That's what the official document says, but I don't know how to write it in vue.

![image](https://user-images.githubusercontent.com/24537314/48888234-f7702280-ee6c-11e8-8b5e-809de66ba6f6.png)
![image](https://user-images.githubusercontent.com/24537314/48888244-03f47b00-ee6d-11e8-9c31-8ada57ee8d6f.png)

**Comment by khoanguyen96** [comment]
Hey @mjfxdd,

Sorry for the late reply! I checked the PayPal docs and you're right this doesn't seem to be exposed in the component anywhere. I'll make a slight addition where you can pass in an `shipping-address` prop.

Side note, I'm currently not very happy how some of the props are completely different to how PayPal has it laid out but this can be tackled in another issue.

**Comment by khoanguyen96** [comment]
Hey @mjfxdd,

Just an update I released v3.2.0, which should have the `shipping_address` prop available for you to use.

Thanks!
