### ISSUE TITLE
document dev="true" as sandbox

### ISSUE THREAD

**Issue by janzheng** [khoanguyen96/vue-paypal-checkout#9]
Hey, I think your wrapper is great! But could you document setting :dev="true" as setting env="sandbox"?
Or I would also suggest using :env="sandbox" or :env="production" in your wrapper to mimic the same language as the component. 

Cheers!

**Comment by khoanguyen96** [comment]
Hey,

Thanks for the suggestion! This definitely makes more sense. I'll publish the change soon.

**Comment by janzheng** [comment]
That was fast! Keep up the good work
