### ISSUE TITLE
onInit, onClick events with form validation?

### ISSUE THREAD

**Issue by goors** [khoanguyen96/vue-paypal-checkout#94]
How can I use this with your plugin?

https://developer.paypal.com/docs/checkout/integration-features/validation/#asynchronous-validation

I tried to modify it but it seems that this part of PayPal npm package is missing actions:

```
onClick: {
      type: 'function',
      required: false,
      noop: true,
      decorate: function decorate(original) {
        return function decorateOnClick(data) {
```

Long story short how can you validate form first and then allow PayPal actions to proceed?

**Comment by Kinzi** [comment]
@goors Where you able to solve this somehow?

**Comment by goors** [comment]
@Kinzi  nope. I was never able to resolve this. that PayPal button sucks!
